name 'dhoppe-bash'
version '0.0.5'

author 'Dennis Hoppe'
license 'GPLv2'
project_page 'http://github.com/dhoppe/puppet-bash'
source 'git://github.com/dhoppe/puppet-bash'
summary 'BASH Module'
description 'BASH Module for Debian, Ubuntu'
dependency 'dhoppe/puppet', '>=0.0.1'
